language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx
gemfile:
  - Gemfile
matrix:
  exclude:
    # Nokogiri 1.3.3 is not compatible with Rubinius or JRuby
    - gemfile: Gemfile
      rvm: rbx
    - gemfile: Gemfile
      rvm: jruby-19mode
before_install:
  - CHROMEDRIVER_VERSION=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - CHROMEDRIVER_URL="http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
  - FILE=`mktemp`; wget "$CHROMEDRIVER_URL" -qO $FILE && sudo unzip $FILE chromedriver -d /usr/local/bin; rm $FILE; sudo chmod 777 /usr/local/bin/chromedriver
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sudo chmod 1777 /dev/shm
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script: "bundle exec cucumber"